[env]
# load env from the dotenv file after tools have defined environment variables
_.file = { path = ".env", tools = true }

[tools]
kubectl = "latest"
flux2 = "latest"
kubectx = "latest"
kubens = "latest"
